{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Minimum delivery time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "region1_minimum_delivery_time" }
   ]
  },
  {
   "title": "Maximum delivery time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "region1_maximum_delivery_time" }
   ]
  },
  {
   "title": "Average delivery time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "region1_average_delivery_time" }
   ]
  },
  {
   "title": "Number of restaurant zip code operate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "region1_number_of_zip_codes" }
   ]
  },
  {
   "title": "Cuisine with max review",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "region1_cuisine_with_maximum_review"
    }
   ]
  }
 ]
}