global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
#   - 'alert.rules'
#   - "first.rules"
#   - "second.rules"

# alert
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
#            - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['kpi-publisher:8084']


