apiVersion: 1

deleteDatasources:
  - name: prometheus-ds
    orgId: 1

datasources:
  - name: prometheus-ds
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    user:
    password:
    database:
    basicAuth: false
    basicAuthUser:
    basicAuthPassword:
    withCredentials:
    isDefault: true
    jsonData:
      tlsAuth: false
      tlsAuthWithCACert: false
    secureJsonData:
      tlsCACert: ""
      tlsClientCert: ""
      tlsClientKey: ""
    version: 1
    readOnly: false